"""Setup wizard logic for familiar-ai first-run configuration.

This module provides:
- is_first_run(): detect whether .env has been configured
- SetupConfig: dataclass collecting all configurable settings
- generate_env_file(): write a .env from SetupConfig
- validate_anthropic_key(): format-check an Anthropic API key
- validate_camera_connection(): test ONVIF connectivity
- discover_onvif_cameras(): WS-Discovery scan for cameras on LAN
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# First-run detection
# ---------------------------------------------------------------------------


def is_first_run(env_dir: Path | None = None) -> bool:
    """Return True if no .env file exists in *env_dir* (defaults to cwd)."""
    base = env_dir or Path.cwd()
    return not (base / ".env").exists()


# ---------------------------------------------------------------------------
# Setup configuration
# ---------------------------------------------------------------------------


@dataclass
class SetupConfig:
    """All settings that can be configured through the setup wizard."""

    # Required
    anthropic_api_key: str

    # Optional — Anthropic
    anthropic_model: str = ""

    # Optional — Camera
    camera_host: str = ""
    camera_username: str = ""
    camera_password: str = ""
    camera_onvif_port: str = "2020"

    # Optional — TTS
    elevenlabs_api_key: str = ""
    elevenlabs_voice_id: str = ""

    # Optional — extra (rarely needed at setup)
    extra: dict[str, str] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# .env generation
# ---------------------------------------------------------------------------

_ENV_HEADER = """\
# familiar-ai configuration — generated by setup wizard
# Edit this file to change settings, then restart.

# Anthropic API (required)
ANTHROPIC_API_KEY={anthropic_api_key}
"""

_CAMERA_BLOCK = """\

# Camera — ONVIF/RTSP
CAMERA_HOST={camera_host}
CAMERA_USERNAME={camera_username}
CAMERA_PASSWORD={camera_password}
CAMERA_ONVIF_PORT={camera_onvif_port}
"""

_ELEVENLABS_BLOCK = """\

# ElevenLabs TTS
ELEVENLABS_API_KEY={elevenlabs_api_key}
"""

_MODEL_LINE = "ANTHROPIC_MODEL={model}\n"


def generate_env_file(config: SetupConfig, path: Path | None = None) -> Path:
    """Write a .env file from *config*. Returns the path written to.

    Creates parent directories if needed.
    """
    env_path = path or Path.cwd() / ".env"
    env_path.parent.mkdir(parents=True, exist_ok=True)

    content = _ENV_HEADER.format(anthropic_api_key=config.anthropic_api_key)

    if config.anthropic_model:
        content += _MODEL_LINE.format(model=config.anthropic_model)

    if config.camera_host:
        content += _CAMERA_BLOCK.format(
            camera_host=config.camera_host,
            camera_username=config.camera_username,
            camera_password=config.camera_password,
            camera_onvif_port=config.camera_onvif_port,
        )

    if config.elevenlabs_api_key:
        content += _ELEVENLABS_BLOCK.format(
            elevenlabs_api_key=config.elevenlabs_api_key,
        )

    for key, value in config.extra.items():
        content += f"{key}={value}\n"

    env_path.write_text(content, encoding="utf-8")
    return env_path


# ---------------------------------------------------------------------------
# API key validation
# ---------------------------------------------------------------------------

_ANTHROPIC_KEY_RE = re.compile(r"^sk-ant-")


def validate_anthropic_key(key: str) -> tuple[bool, str]:
    """Check Anthropic API key format. Returns (ok, error_message).

    Does NOT make a network call — format check only.
    """
    if not key:
        return False, "API key cannot be empty"
    if not _ANTHROPIC_KEY_RE.match(key):
        return False, "Anthropic API keys must start with 'sk-ant-'"
    return True, ""


# ---------------------------------------------------------------------------
# Camera: ONVIF stub / real import
# ---------------------------------------------------------------------------

try:
    from onvif import ONVIFCamera  # type: ignore[import]
except ImportError:

    class ONVIFCamera:  # type: ignore[no-redef]
        """Stub when onvif-zeep-async is not installed."""

        def __init__(self, *args: Any, **kwargs: Any) -> None:
            raise ImportError(
                "onvif-zeep-async is required for camera support. "
                "Install with: pip install 'familiar-ai[camera]'"
            )

        def create_devicemgmt_service(self) -> None:
            pass


# ---------------------------------------------------------------------------
# Camera connection test
# ---------------------------------------------------------------------------


async def validate_camera_connection(
    host: str, username: str, password: str, port: int = 2020
) -> tuple[bool, str]:
    """Test ONVIF connectivity. Returns (ok, error_message)."""
    try:
        cam = ONVIFCamera(host, port, username, password)
        cam.create_devicemgmt_service()
        return True, ""
    except Exception as exc:
        return False, str(exc)


# ---------------------------------------------------------------------------
# ONVIF WS-Discovery
# ---------------------------------------------------------------------------


async def _ws_discover() -> list[Any]:
    """Run ONVIF WS-Discovery and return raw service objects.

    Isolated as its own async function so tests can patch it cleanly.
    """
    try:
        import asyncio
        from wsdiscovery import WSDiscovery  # type: ignore[import]

        def _sync() -> list[Any]:
            wsd = WSDiscovery()
            wsd.start()
            svcs = wsd.searchServices()
            wsd.stop()
            return svcs

        return await asyncio.to_thread(_sync)
    except ImportError:
        logger.debug("wsdiscovery not available — camera auto-discovery disabled")
        return []


async def discover_onvif_cameras(timeout: float = 3.0) -> list[dict[str, str]]:
    """Scan the local network for ONVIF cameras via WS-Discovery.

    Returns a list of dicts with at minimum {'host': str}.
    Returns an empty list on any error (missing deps, network issues, etc.).
    """
    import asyncio

    try:
        services = await asyncio.wait_for(_ws_discover(), timeout=timeout)
    except Exception as exc:
        logger.debug("Camera discovery error: %s", exc)
        return []

    results: list[dict[str, str]] = []
    for svc in services:
        try:
            addrs = svc.getXAddrs()
            if not addrs:
                continue
            parsed = urlparse(addrs[0])
            host = parsed.hostname or ""
            if host:
                results.append({"host": host, "address": addrs[0]})
        except Exception:
            continue
    return results
